
= vdb-datafederation

|===
|Level |Technologies |Target Product |Product Versions |Source

|Basic
|Teiid, VDB, Native Queries, VDB reuse, reading data from JDBC, delimited file and Excel File
|DV
|DV 6.0+
|https://github.com/teiid/teiid-quickstarts
|===

vdb-datafederation is the 'Hello World' example for Teiid.

== VDB

* Portfolio - source models, view’s, native query

== What is it?

This quickstart demonstrates how to define a vdb to enable data federation across multiple data sources (i.e., relational and text file). This will demonstrate the following:

* how to federate data from a relational data source, a text file-based data source and an EXCEL File
* how to define a view using DDL
* how to define a translator override to support native queries
* how to define a second vdb that reuses (extends) another vdb

This example uses the H2 database, which is referenced as the "accounts-ds" data source in the server, but the creation SQL can be adapted to another database if you choose.

NOTE: this example provides the base setup for which other quick starts depend upon.

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]

== Setup

=== 1. Start the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux 
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 2. Copy teiid support files

* Copy the "teiidfiles" directory to the $JBOSS_HOME/ directory

The src/teiidfiles directory should contain:

----
customer-schema.sql
customer-schema-drop.sql
data/marketdata-price.txt
data/marketdata-price1.txt
----

when complete, you should see $JBOSS_HOME/teiidfiles

=== 3. Setup the h2 datasource and file resource adapter

* run the following CLI script

----
cd $JBOSS_HOME/bin
./jboss-cli.sh --connect --file=\{path}/vdb-datafederation/src/scripts/setup.cli
----

=== 4. VDB Deployment:

Copy (deploy) the Portfolio VDB related files to the $JBOSS_HOME/standalone/deployments directory

----
src/vdb/portfolio-vdb.xml
src/vdb/portfolio-vdb.xml.dodeploy
----

You should see the server log indicate the VDB is active with a message like: `TEIID40003 VDB Portfolio.1 is set to ACTIVE`. Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed.

See <<Query Demonstrations, Query Demonstrations>> below to demonstrate data federation.

== Query Demonstrations

=== Using the simpleclient

1.  Change your working directory to "${quickstart.install.dir}/simpleclient"
2.  Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="portfolio" -Dsql="example query" -Dusername="xx" -Dpassword="xx"

=== Source and Federated Queries Examples

NOTE: For the following examples, use the vdb: Portfolio

* Example a - queries the relational source.

[source,sql]
----
select * from product
----

* Example b - queries the text file-based source.

[source,sql]
----
select stock.* from (call MarketData.getTextFiles('*.txt')) f, TEXTTABLE(f.file COLUMNS symbol string, price bigdecimal HEADER) stock
----

* Example c - performs a join between the relational source and the text file-based source. The files returned from the getTextFiles procedure are passed to the TEXTTABLE table function (via the nested table correlated reference f.file). The TEXTTABLE function expects a text file with a HEADER containing entries for at least symbol and price columns.

[source,sql]
----
select product.symbol, stock.price, company_name from product, (call MarketData.getTextFiles('*.txt')) f, TEXTTABLE(f.file COLUMNS symbol string, price bigdecimal HEADER) stock where product.symbol=stock.symbol
----

* Example d - queries the EXCEL file to retrieve other personal holdings valuations. 

[source,sql]
----
select * from OtherHoldings.PersonalHoldings
----

=== Native Query

NOTE: For the following examples, use the vdb: Portfolio

* Example a - Issue query that contains a NATIVE sql call that will be directly issued against the H2 database. This is useful if the function isn't supported by the translator (check the documentation for the types of translators that support NATIVE sql). Note that the translator override in the vdb xml enabling support for native queries has to be set. 

[source,sql]
----
select x.* FROM (call native('select Shares_Count, MONTHNAME(Purchase_Date) from Holdings')) w, ARRAYTABLE(w.tuple COLUMNS "Shares_Count" integer, "MonthPurchased" string ) AS x
----
