link:./Legal_Notice.adoc[Legal Notice]

= Teiid Quickstarts

This Quick Start Guide takes you through an introduction to the concepts important to Teiid, downloading the software, building and deploying a virtual database and integrating data sources. The goal is to provide you with examples that help explain how to use to Teiid in order to get you off the ground.  It also introduces to some of the essential concepts of Teiid.

TIP: **Further Reading** - Please read https://teiid.gitbooks.io/documents/content/[Teiid Documentation] to understand different terminologies used, resources needed, and artifacts to be generated before developing a successful application. This example takes advantage of only a minimal set of features in Teiid for the sake of simplicity and time.

NOTE: **Ask Us** - Ask us any questions you have on this Quick Start or any other Teiid related questions on https://community.jboss.org/en/teiid?view=discussions[Teiid Forums].

== Introduction

Quick starts for http://teiid.jboss.org/[Teiid].

To contribute a quick start, goto http://github.com/teiid/teiid-quickstarts.

The link:dist[dist] folder contains the Maven scripts to build the quick start zip of the quickstarts.

Be sure to read this entire document before you attempt to work with the quickstarts. It contains the following information:

* <<Available Quickstarts, Available Quickstarts>>: List of the available quickstarts, a description and demonstrated features for each one.
* <<System Requirements, System Requirements>>: List of software required to run the quickstarts.
* <<Run the Quick Starts, Run the Quick Starts>>: General instructions for building, deploying, and running the quickstarts.

== Available Quickstarts

The following is a list of the currently available quickstarts. The table lists each quickstart name, the features it demonstrates, and it gives a brief description of the quickstart. For more detailed information about a quickstart, click on the quickstart name.

Some quickstarts are designed to enhance or extend other quickstarts. These are noted in the *Prerequisites* column. If a quickstart lists prerequisites, those must be installed or deployed before working with the quickstart.

|===
|*Quickstart Name* |*Features Demonstrated* |*Description* |*Prerequisites*

|link:vdb-datafederation/README.adoc[datafederation] 
|Data Federation, TEXTTABLE, Native Query, VDB Reuse, External Materialization, Excel File
|Shows how to expose multiple data sources for data federation and externally materialize a view to improve performance 
|None

|link:vdb-dataroles/README.adoc[dataroles] 
|Data roles 
|Shows how to control Read/Write data access using data roles and masking
|datafederation

|link:webservices-as-a-datasource/README.adoc[consume-webservices] 
|'ws' Translator, XMLTABLE, XMLPARSE, VIEW DDL 
|Demonstrates the use of the 'ws' translator to read a web service data source 
|None

|link:hibernate-on-top-of-teiid/README.adoc[hibernate] 
|Hibernate Integration, VDB ReUse, Create VIEW, Create Trigger, TEXTTABLE
|Demonstrates how a Hibernate application can add data federation capabilities at the data layer 
|datafederation

|link:jdg-local-cache/README.adoc[jdg local cache] 
|'infinispan' Object Translator, OBJECTTABLE 
|Demonstrates reading reading a JDG cache running in library mode 
|None

|link:jdg-remote-cache/README_JDG_REMOTE_QUERY_DSL.md[jdg remote cache using dsl] 
|'infinispan' DSL Translator 
|Demonstrates reading from a remote JDG cache using hot rod client that’s configured using protobuffers 
|None

|link:simpleclient/README.adoc[simpleclient] |Teiid JDBC Connection
|Demonstrates how to make a jdbc connection to Teiid using the Teiid
JDBC Driver and DataSource |None

|link:tpch/README.adoc[tpch] |Performance, Data Federation |Measures
performance using TPC-H benchmark against two running Postgresql servers
|2 running PostgresSQL servers, Unix machine host

|link:ldap-as-a-datasource/README.adoc[ldap-as-a-datasource] 
|'ldap' Translator, FOREIGN TABLE DDL, OpenLDAP 
|Demonstrates using the ldap Translator to access data in OpenLDAP Server 
|OpenLDAP be installed, Groups 'HR' and Users under it be configured

|link:mongodb-as-a-datasource/README.adoc[mongodb-as-a-datasource]
|'mongodb' Translator, FOREIGN TABLE DDL 
|Demonstrates using the mongodb Translator to access documents in mongodb 
|MongoDB be installed, docuemnts be inserted under 'Employee' connection

|link:hbase-as-a-datasource/README.adoc[hbase-as-a-datasource] 
|'hbase' Translator, FOREIGN TABLE DDL 
|Demonstrates using the Hbase Translator via the Pheonix driver 
|Hbase be installed

|link:drools-integration/README.adoc[drools-integration] 
|Drools integration, UDF, FOREIGN Function DDL 
|Demonstrates using a simple rules invocation via a Function
|None

|link:hive-as-a-datasource/README.adoc[hive-as-a-datasource] 
|HDFS/Hive integration, Teiid, VDB, View, Hive Translator 
|Demonstrates using Hive translator to access data in Hadoop/Hive
|Hadoop Services, HiveServer2
|===

== System Requirements

To run these quickstarts with the provided build scripts, you need the following:

1.  Java 1.7 or latter, to run {{ book.asName }} and Maven. You can choose from the following:
* OpenJDK
* Oracle Java SE
* Oracle JRockit

2.  Maven 3.0.0 or newer, to build and deploy the examples
* If you have not yet installed Maven, see the http://maven.apache.org/guides/getting-started/index.html[Maven Getting Started Guide] for details.
* If you have installed Maven, you can check the version by typing the following in a command line:

[source,java]
----
mvn --version 
----

3.  The JBoss Enterprise Application Platform (EAP) 6 distribution ZIP or the {{ book.asName }} distribution ZIP that’s compatible with Teiid.
* For information on how to install and run {{ book.asName }}, refer to the server documentation.

4.  Set JBOSS_HOME to the root directory location of your applicationserver, the scripts use this variable to determine where to deploy to.

== Run the Quick Starts

The root folder of each quickstart contains a README file with specific details on how to build and run the example.

Open a command line and navigate to the root directory of the quickstart you want to run.
