
= Connecting to Teiid

The Connecting to Teiid will assist in demonstrating how to make a connection to Teiid using either the JDBC Driver/DataSource or a graphical SQuirreL SQL Client. Note, this process is no different than connecting to any other JDBC sources like Oracle.

Now that, there are many different ways to connect to Teiid:

* Use JDBC, if you are writing a Java based application. See details here https://teiid.gitbooks.io/documents/content/client-dev/JDBC_Support.html
* Use ODBC, if you are using C/C++/C#/Node.js type applications. See https://teiid.gitbooks.io/documents/content/client-dev/ODBC_Support.html
* Use OData, if you want to REST based services. See https://teiid.gitbooks.io/documents/content/client-dev/OData_Support.html

== Sample Client

Refer to link:../simpleclient/README.adoc[simpleclient/README.adoc] for details.

NOTE: If you are using a graphical client, such as http://www.squirrelsql.org/[SQuirreL], have a look at the metadata tree to see not only what is exposed by your VDB, but also the SYS schema tables.

If your application is Web based, you can create a data source for your VDB and treat it as any other JDBC source using org.teiid.jdbc.TeiidDataSource and assigning it a JNDI name. Refer to https://teiid.gitbooks.io/documents/content/client-dev/WildFly_DataSource.html[Client Developer's Guide - Datasource] for more information on creating a DataSource.

== Standalone Java Application

Before you can make a JDBC connection to the Teiid VDB, add the Teiid's JDBC driver jar file to your application's classpath. This JDBC Driver jar file is available for download from ﻿http://teiid.jboss.org/downloads/[Teiid Downloads].

[source,java]
----
teiid-{version}-jdbc.jar
----

For a Java application to connect to a JDBC source, it needs a URL, user-id, and password. To connect to your VDB, you need a URL and any additional optional properties that you would like to set. Teiid defaults to allowing access when username is "user" and password as "user". Additional user accounts can be added. A JDBC connection can be obtained through the Teiid driver "org.teiid.jdbc.TeiidDriver" with the URL syntax of

[source,java]
----
jdbc:teiid:<VDB-Name>@mm(s)://<host name>:<port>
----

You can add optional properties at the end of the URL using a semi-colon(;) name=value format. For example

[source,java]
----
jdbc:teiid:<VDB-Name>@mm(s)://<host name>:<port>;user=user;password=user
----

Check out https://teiid.gitbooks.io/documents/content/client-dev/Client_Developers_Guide.html[Client Developer's Guide] for all the optional connection properties in your URL. Here is sample code showing how to make JDBC connection.

[source,java]
.*Sample JAVA Code - Create Driver Connection*
----
String url = "jdbc:teiid:DynamicPortfolio@mm://localhost:31000";
Class.forName("org.teiid.jdbc.TeiidDriver");
Connection conn = DriverManager.getConnection(url, "user", "password");
----

You can also use `org.teiid.jdbc.TeiidDataSource` to make connection in your Java application. For example, you can use following code fragment to make a connection to the VDB and issuing the query exactly the same as in the above example:

[source,java]
.*Sample JAVA Code - Create DataSource Connection*
----
TeiidDataSource ds = new TeiidDataSource();
ds.setDatabaseName("DynamicPortfolio");
ds.setUser("user");
ds.setPassword("user");
ds.setServerName("host");
ds.setPortNumber("port");
Connection connection = ds.getConnection();
----

The TeiidDataSource also provides an option to set optional parameters using the "set" methods on the data source. For all the allowable data source properties, check out https://teiid.gitbooks.io/documents/content/client-dev/Client_Developers_Guide.html[Client Developer's Guide].

NOTE: **Remote Server** - If your Teiid client and server are not installed on same machine, then you have to bind JBoss AS IP address on to something other than 127.0.0.1 Contact your system administrator for the IP address you can use for that machine so that it can be remotely accessible. Once you have IP address or hostname you can update the standalone-teiid.xml file under "interfaces" section. Once you restart the server, then you can specify the correct IP address or hostname in the Teiid client driver to make the remote connection to the VDB.
