
= vdb-materialization Quickstart

|===
|Level |Technologies |Target Product |Product Versions |Source

|Advanced
|Teiid, Materialization
|DV
|DV 6.0+
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

vdb-materialization demonstrates how to configure external/internal materialization(https://teiid.gitbooks.io/documents/content/caching/Materialized_Views.html[document external/internal materialization]), so that caching can be used to improve query performance.

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]

NOTE: This example relies upon the vdb-datafederation example and that it needs to be deployed prior to running this example. Therefore, read the vdb-datafederation's README and follow its directions before continuing.

== Setup

=== 1. Run vdb-datafederation

Refer to link:../vdb-datafederation/README.adoc[vdb-datafederation/README.adoc] to run vdb-datafederation.

=== 2. Setup the server

Refer to link:../categories/prerequisites.adoc#_start_the_server[Prerequisites] to start the Server.

=== 3. VDB Deployment

Copy the following files to the "/standalone/deployments" directory

----
src/vdb/portfolio-mat-vdb.xml
src/vdb/portfolio-mat-vdb.xml.dodeploy
src/vdb/portfolio-intermat-vdb.xml
src/vdb/portfolio-intermat-vdb.xml.dodeploy
----

You should see the server log indicate the VDB is active with a message like: `TEIID40003 VDB PortfolioMaterialize.1 is set to ACTIVE` and `TEIID40003 VDB PortfolioInterMaterialize.1 is set to ACTIVE`. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate data materialization.

== Query Demonstrations

link:../simpleclient/README.adoc#_execution[Simple Java Client] for sample SQL Queries, link:../simpleclient/SQuirreL.adoc[SQuirreL Client] for a fully featured SQL Queries.

[source,sql]
.*Example - Query the external materialized View*
----
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="select * from StocksMatModel.stockPricesMatView"
----

[source,sql]
.*Example - Query the internal materialized View*
----
mvn exec:java -Dvdb="PortfolioInterMaterialize" -Dsql="select * from StocksMatModel.stockPricesInterMatView"
----

[source,sql]
.*Example - Query external materialization*
----
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="select * from StocksMatModel.stockPricesMatView"
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="INSERT INTO PRODUCT (ID,SYMBOL,COMPANY_NAME) VALUES(2000,'RHT','Red Hat Inc')"
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="select * from StocksMatModel.stockPricesMatView"
----

NOTE: First, execute `select * from StocksMatModel.stockPricesMatView` will get 18 rows, insert a new row into Product table(`INSERT INTO PRODUCT (ID,SYMBOL,COMPANY_NAME) VALUES(2000,'RHT','Red Hat Inc')`), wait 1 minute, as defined by: "teiid_rel:MATVIEW_TTL" 60000 in the portfolio-vdb.xml, re-execute `select * from StocksMatModel.stockPricesMatView` will get 19 rows,


[source,sql]
.*Example - Query the original source*
----
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="select * from StocksMatModel.stockPricesMatView option nocache"
----

[source,sql]
.*Example - Query Materialized view status*
----
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="EXEC SYSADMIN.matViewStatus('StocksMatModel', 'stockPricesMatView')"
mvn exec:java -Dvdb="PortfolioInterMaterialize" -Dsql="EXEC SYSADMIN.matViewStatus('StocksMatModel', 'stockPricesInterMatView')"
----

[source,sql]
.*Example - Perform a complete refresh*
----
mvn exec:java -Dvdb="PortfolioMaterialize" -Dsql="EXEC SYSADMIN.loadMatView('StocksMatModel', 'stockPricesMatView')"
mvn exec:java -Dvdb="PortfolioInterMaterialize" -Dsql="EXEC SYSADMIN.loadMatView('StocksMatModel', 'stockPricesInterMatView')"
----

[source,sql]
.*Example - SQL*
----
select * from StocksMatModel.stockPricesMatView 
select * from StocksMatModel.stockPricesInterMatView
INSERT INTO PRODUCT (ID,SYMBOL,COMPANY_NAME) VALUES(2000,'RHT','Red Hat Inc')
select * from StocksMatModel.stockPricesMatView option nocache
EXEC SYSADMIN.matViewStatus('StocksMatModel', 'stockPricesMatView')
EXEC SYSADMIN.loadMatView('StocksMatModel', 'stockPricesInterMatView')
EXEC SYSADMIN.loadMatView('StocksMatModel', 'stockPricesMatView')
EXEC SYSADMIN.loadMatView('StocksMatModel', 'stockPricesInterMatView')
----
