
= vdb-materialization Quickstart

|===
|Level |Technologies |Target Product |Product Versions |Source

|Advanced
|Teiid, Materialization
|DV
|DV 6.0+
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

vdb-materialization demonstrates how to configure external/internal materialization, so that caching can be used to improve query performance.

* VDB: PortfolioMaterialize

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]

NOTE: This example relies upon the vdb-datafederation example and that it needs to be deployed prior to running this example. Therefore, read the vdb-datafederation's README and follow its directions before continuing.

== Setup

=== 1. Run vdb-datafederation

Refer to link:../vdb-datafederation/README.adoc[vdb-datafederation/README.adoc] to run vdb-datafederation.

=== 2. Setup the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 3. VDB Deployment

Copy the following files to the "/standalone/deployments" directory

----
src/vdb/portfolio-mat-vdb.xml
src/vdb/portfolio-mat-vdb.xml.dodeploy
----

Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate data materialization.

== Query Demonstrations

=== Using the simpleclient

1.  Change your working directory to "${quickstart.install.dir}/simpleclient"
2.  Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="portfolio" -Dsql="example query" -Dusername="xx" -Dpassword="xx"

NOTE: For the following examples, use the vdb: PortfolioMaterialize

* Example a - Query the materialized View

[source,sql]
----
select * from StocksMatModel.stockPricesMatView (should get 18 rows)
----

* Example b - Add a row to the product table, so that when the materialized view is updated, the new row will be picked

First, insert a new row into Products table:

[source,sql]
----
INSERT INTO PRODUCT (ID,SYMBOL,COMPANY_NAME) VALUES(2000,'RHT','Red Hat Inc')
----

wait 1 minute, as defined by: "teiid_rel:MATVIEW_TTL" 60000, in the portfolio-vdb.xml

then re-issue query in "a" and should now see 19 rows

* Example c - Issue a query that bypasses the cached data, and queries the original source

[source,sql]
----
select * from StocksMatModel.stockPricesMatView option nocache (should be the same as "b")
----
