
= JDG Local-Cache (Library Mode) Materialization Quickstart

|===
|Level |Technologies |Target Product |Product Versions |Source

|Intermediate
|Teiid, Infinispan Library Mode, Materialization
|DV, JDG
|DV 6.1+, JDG 6.5+
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

This quickstart demonstrates how to configure an external materialization cache to improve performance when reading the data

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]
* link:../vdb-datafederation/README.adoc[vdb-datafederation] quickstart needs to be installed.
* JDG 6.5+ eap modules kit 

NOTE: can obtain JDG kit distributions on Red Hat's Customer Portal at https://access.redhat.com/jbossnetwork/restricted/listSoftware.html

== Setup

=== 1. JDG Setup

Install the JBoss Data Grid eap modules kit into the modules location for your Wildfly - Teiid instance. See Red Hat: http://access.redhat.com to obtain the kit.

=== 2. Teiid Server Setup

* Build quickstart artifacts via

----
mvn clean install
----

This will build jdg-quickstart-wildfly-dist.zip in the target directory.

* Deploy the distribution kit

Unzip the target/jdg-quickstart-wildfly-dist.zip at the root of the JBOSS_HOME directory. This will deploy the pojo module and the cache configuration file.

* Update module dependencies

[Required] The org.infinispan.commons (slot="${jdg.slot}" or slot for version installed) module needs to have the pojo dependency added

[Optional] If the version of JDG modules you installed was not ${jdg.slot}, then update the following modules:

----
org.jboss.teiid.translator.infinispan.libmode
org.jboss.teiid.resource-adapter.infinispan.libmode
----

* Configure resource-adapter

Open the file: {JBOSS_HOME}/docs/teiid/datasources/infinispan-library-mode/infinispan-lib-mode-materialization-ds.xml, copy and paste the resource-adapter section it into the server configuration, under the section.

* Start the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 3.  Install the infinispan-libmode translator

----
cd ${JBOSS_HOME}/bin
./jboss-cli.sh --connect --file=../docs/teiid/datasources/infinispan-library-mode/add-ispn-lib-mode-translator.cli
----

=== 4. deploy the VDB

Deploy VDB for materialization from directory src/vdb, copy files jdg-local-cache-mat-vdb.xml and jdg-local-cache-mat-vdb.xml.dodeploy to {JBOSS_HOME}/standalone/deployments

[[query-demonstrations]]
Query Demonstrations
--------------------

Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate query.

== Query Demonstrations

1. Change your working directory to "${quickstart.install.dir}/simpleclient"
2. Use the simpleclient example to run the following queries:


Example: mvn exec:java -Dvdb="StocksMat" -Dsql="examplequery" -Dusername="teiidUser" -Dpassword="pwd"

or

1.  Use a sql tool, like SQuirreL, to connect and issue following example queries(connect URL: jdbc:teiid:StocksMat@mm://localhost:31000)

[source,sql]
.*Example Queries for using jdg-local-cache-mat-vdb.xml*
----
select productId, symbol, price, companyname from StocksMatModel.stockPricesMatView
----

To see materialization and confirm the process is working, do the following:

[source,sql]
----
Insert into Product (ID, SYMBOL, COMPANY_NAME) Values (2000, 'RHT', 'RedHat Inc')
----

Wait for 2 mins - the refresh is set to 60 secs, but depending on when the insert occurred on the refresh cycle, it could take close to 2 minutes. Reissue query: 

[source,sql]
----
select name, id, email from PersonMatModel.PersonMatView
----

and should see the RHT stock.
