
= Prerequisites
:toc: manual
:toc-placement: preamble

This page including instructions for installing or set up Quick start Prerequisites

== Downloading and installing Java

First things first, Teiid Server and Teiid Quick Starts needs at least a Java Runtime Environment (aka JRE) version 1.7, but as we will also develop some applications, we will need a Java Development Kit(aka JDK).

Downloading Java 7 or later version:

* http://openjdk.java.net/install/[OpenJDK]
* http://www.oracle.com/technetwork/java/javase/index-137561.html[Oracle]

[source,java]
.*Example of Install OpenJDK on Fedora*
----
$ tar zxvf jdk-8u25-linux-x64.tar.gz -C ~/jdk8

$ export JAVA_HOME=~/jdk8
$ export PATH=$JAVA_HOME/bin:$PATH

$ java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
----

NOTE: If you are a system administrator you might want to download and install only the JRE package.

== Downloading and installing Maven

To run Teiid Quick Starts needs Maven 3. Download Maven from http://maven.apache.org/. Follow the official Maven installation guide if you don't already have Maven 3 installed. 

[source,java]
.*Example of install Maven on Fedora*
----
$ unzip apache-maven-3.2.5-bin.zip

$ export M3_HOME="/usr/maven/apache-maven-3.2.5"  
$ export PATH="$M3_HOME/bin:$PATH"  
$ export MAVEN_OPTS="-Xms256m -Xmx1024m -XX:MaxPermSize=512m"  

$ mvn --version
Apache Maven 3.2.5
----

NOTE: In Linux Server(Fedora/Red Hat Linux), edit .bash_profile add `mvn` to path. 

== Downloading and installing Teiid

To run the Teiid Quick Starts needs Teiid Server. Download Teiid Server(Teiid Runtime) from http://teiid.jboss.org/downloads/.

[source,java]
.*Example of install Teiid on Fedora*
----
$ unzip teiid-9.0.0.Final-wildfly-server.zip
----

Refer to https://teiid.gitbooks.io/documents/content/admin/Installation_Guide.html[Teiid Installation] guide for more details.

=== Installing Teiid from souce code

Alternatively, you can install Teiid Server from https://github.com/teiid/teiid[source code].

After <<Downloading and installing Java, Downloading and installing Java>>, <<Downloading and installing Maven, Downloading and installing Maven>> and https://help.github.com/articles/set-up-git/[Set Up Git], clone https://github.com/teiid/teiid[source code], build Teiid Server dist:

[source,java]
----
$ git clone https://github.com/<yourname>/teiid.git
$ cd teiid
$ mvn clean install -P release -Dmaven.javadoc.skip=true -s settings.xml
----

To install Teiid Server in Standalone Mode:

[source,java]
----
$ unzip build/target/teiid-VERSION-SNAPSHOT-wildfly-server.zip
$ cd teiid-VERSION/
$ ./bin/standalone.sh  
$ ./bin/jboss-cli.sh --connect --file=bin/scripts/teiid-standalone-mode-install.cli 
---- 

To install Teiid Server in Domain Mode:

[source,java]
----
$ unzip build/target/teiid-VERSION-SNAPSHOT-wildfly-server.zip
$ cd teiid-VERSION/
$ ./bin/domain.sh
$ ./bin/jboss-cli.sh --connect --file=bin/scripts/teiid-domain-mode-install.cli 
----

The User including dashboardUser, teiidUser, restUser, odataUser, ManagementUser are necessary for running Teiid Quick Starts, use create-user script to create:

[source,java]
----
$ ./bin/add-user.sh -a -u dashboardAdmin -p password1! -g admin  
$ ./bin/add-user.sh -a -u teiidUser -p password1! -g user  
$ ./bin/add-user.sh -a -u restUser -p password1! -g rest  
$ ./bin/add-user.sh -a -u odataUser -p password1! -g odata  
$ ./bin/add-user.sh admin password1!
----

