
|===
|Level |Technologies |Target Product |Product Versions |Source

|Beginners
|Teiid, HBase Translator, Foreign Table
|DV
|DV 6.1
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

*hbase-as-a-datasource* demonstrates using the HBase Translator with Phoenix Data Source to access data in HBase.

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]
* HBase Server, Phoenix Driver

== Setup and Deployment

=== 1. Start the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 2. Setup HBase

* Using http://hbase.apache.org/book.html#quickstart[HBase quickstart steps] to install a single-node, standalone instance of HBase,

----
$ tar -xvf hbase-0.98.8-hadoop2-bin.tar.gz
$ cd hbase-0.98.8-hadoop2/
----

* Download Phoenix 4.x from http://phoenix.apache.org/download.html[Phoenix Downloads Page], install Phoenix via copying phoenix-core.jar to HBase lib directory,

----
$ tar -xvf phoenix-4.2.1-bin.tar.gz
$ cp phoenix-4.2.1-bin/phoenix-core-4.2.1.jar hbase-0.98.8-hadoop2/lib/
----

* Start HBase and connect to HBase via shell, create table and put sample data in link:src/scripts/customer_sample_data.txt[customer_sample_data.txt], 

----
$ ./bin/start-hbase.sh
$ ./bin/hbase shell
hbase(main):002:0> create 'Customer', 'customer', 'sales'
hbase(main):003:0> put 'Customer', '101', 'customer:name', 'John White'
...
----

=== 3.  Setup Phoenix Data Source

* Copy phoenix-[version]-client.jar and link:src/scripts/setup.cli [setup.cli] to $JBOSS_HOME,

------------------------------------------------------
$ cd $JBOSS_HOME
$ cp {path}/src/scripts/setup.cli ./
$ cp {path}/phoenix-4.2.1-bin/phoenix-4.2.1-client.jar ./
------------------------------------------------------

* Execute CLI commands to setup Phoenix Data Source

----
$ ./bin/jboss-cli.sh --connect --file=setup.cli
----

* Use Phoenix Command Line execute link:src/teiidfiles/customer-schema.sql[customer-schema.sql] to map `Customer` table in HBase, for example

----
$ cd PHOENIX_HOME
$ ./bin/sqlline.py localhost .../src/teiidfiles/customer-schema.sql
----

NOTE: More details about Phoenix Data Sources and Mapping Phoenix table to an existing HBase table please refer to https://teiid.gitbooks.io/documents/content/admin/Phoenix_Data_Sources.html[Teiid Documents].

=== 4. Teiid Deployment

Copy the following files to the "/standalone/deployments" directory

----
src/vdb/hbase-vdb.xml
src/vdb/hbase-vdb.xml.dodeploy
----

Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate query.

== Query Demonstrations

1. Change your working directory to "${quickstart.install.dir}/simpleclient"
2. Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="portfolio" -Dsql="example query" -Dusername="xx" -Dpassword="xx"

The following sql can be used with -Dsql:

[source,sql]
----
SELECT city, amount FROM Customer
SELECT DISTINCT city FROM Customer
SELECT city, amount FROM Customer WHERE PK='105'
SELECT * FROM Customer WHERE PK BETWEEN '105' AND '108'
SELECT * FROM Customer WHERE PK='105' AND name='John White'
SELECT * FROM Customer ORDER BY PK
SELECT * FROM Customer ORDER BY name, city DESC
SELECT name, city, COUNT(PK) FROM Customer GROUP BY name, city
SELECT name, city, COUNT(PK) FROM Customer GROUP BY name, city HAVING COUNT(PK) > 1
----

NOTE: depending on your OS/Shell the quoting/escaping required to run the example can be complicated. It would be better to install a Java client, such as SQuirreL, to run the queries.
