
|===
|Level |Technologies |Target Product |Product Versions |Source

|Basic
|Teiid, VDB, Native Queries, VDB reuse, reading data from JDBC, delimited file, REST Service Through VDB
|DV
|DV 6.1, DV 6.2, DV 6.3
|https://github.com/teiid/teiid-quickstarts
|===

== What is it

This quickstart demonstrates:

* how to define a vdb to enable a https://teiid.gitbooks.io/documents/content/reference/REST_Service_Through_VDB.html[REST Service Through VDB].
* how to use the httpclient api to integrate VDB data via REST
* how to use the Resteasy Client to integrate VDB data via REST
* how to use the Apache CXF WebClient to integrate VDB data via REST
* how to use Swagger API Doc Page test all Rest API.

This quickstart depends upon the link:../vdb-datafederation[vdb-datafederation] quickstart. It needs to be deployed prior to running this example.

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]

This quickstart depends upon the link:../vdb-datafederation[vdb-datafederation] quickstart. It needs to be deployed prior to running this example.

== Setup

=== 1. Run vdb-datafederation

Refer to link:../vdb-datafederation/README.adoc[vdb-datafederation/README.adoc] to run vdb-datafederation.

=== 2. Setup the server

Create a Application User under group `rest`, Navigate to JBOSS_HOME, execute below command will create user `restUser` under group `rest`:

----
$ ./bin/add-user.sh -a -u restUser -p password1! -g rest
----

NOTE: By default, REST services through a VDB are secured with security domain "teiid-security" and with security role "rest".

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 3. Deploy VDB

Copy (deploy) the following VDB related files to the $JBOSS_HOME/standalone/deployments directory

----
src/vdb/portfolio-rest-vdb.xml
src/vdb/portfolio-rest-vdb.xml.dodeploy
----

You should see the server log indicate the VDB is active with a message like: TEIID40003 VDB PortfolioRest.1 is set to ACTIVE. Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate REST Service Through VDB.

== Query Demonstrations

The following Rest API will extract data from the VDB:

* http://localhost:8080/PortfolioRest_1/Rest/foo/1
* http://localhost:8080/PortfolioRest_1/Rest/getAllStocks
* http://localhost:8080/PortfolioRest_1/Rest/getAllStockById/1007
* http://localhost:8080/PortfolioRest_1/Rest/getAllStockBySymbol/IBM

NOTE: Above Query Demonstrations assuming DV server run on localhost.

NOTE: http://localhost:8080/PortfolioRest_1/api will list all API.

=== Run http client

----
$ cd http-client/
$ mvn package exec:java
----

NOTE: If your teiid Server not run on localhost:8080, edit http-client/pom.xml, to make sure arguments point to a correct hostname and port.

=== Run resteasy client

----
$ cd resteasy-client/
$ mvn package exec:java
----

NOTE: If your teiid Server not run on localhost:8080, edit resteasy-client/pom.xml, to make sure arguments point to a correct hostname and port.

=== Run CXF Client

----
$ cd cxf-client/
$ mvn package exec:java
----

NOTE: If your teiid Server not run on localhost:8080, edit cxf-client/pom.xml, to make sure arguments point to a correct hostname and port.
