
|===
|Level |Technologies |Target Product |Product Versions |Source

|Beginner 
|Teiid, VDB, View, Hive Translator, Hive, Hadoop
|DV
|DV 6.0+
|https://github.com/teiid/teiid-quickstarts
|===

== What’s this

This quickstart demonstrates using the Hive translator with HiveServer2 JDBC Driver to access data in Hadoop HDFS. VDB link:src/vdb/hive-vdb.xml[hive-vdb.xml] be used to define View within DDL metadata.

The examples use `java:/HiveDS` referenced with Hive data source, which will be setup by running link:src/scripts/setup.cli[setup.cli]

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* Hadoop, Hive

== Setup

=== 1.Setup Hadoop

Refer to link:../categories/prerequisites.adoc#_installing_hadoop_1_x_to_red_hat_linux[Installing Hadoop 1.x to Red Hat Linux] to finished Hadoop setup.

=== 2. Set up Hive Services

Refer to link:../categories/prerequisites.adoc#_downloading_and_installing_apache_hive[Downloading and installing Apache Hive] to finished Hive setup.

=== 3. Setup Teiid Server

Install Hive driver module. Download TeiidModule-Hive12.zip and copy it into your server installation in the /jboss-eap-6.1/modules folder. unzip it. That's all. Do not modify the $JBOSS_HOME/standlone/configuration/standlone.xml.

Refer to https://developer.jboss.org/wiki/ConnectToAHadoopSourceUsingHive2[ConnectToAHadoopSourceUsingHive2]

Refer to link:../categories/prerequisites.adoc#_start_the_server[Prerequisites] to start the Server.

=== 4. Setup the hive datasource

run the following CLI script

----
cd $JBOSS_HOME/bin
./jboss-cli.sh --connect --file={path}/vdb-Hivehadoop/src/scripts/setup.cli
----

NOTE: Maybe you need modify the connection-url=jdbc:hive2://{host-name}:10000/default to your URL, for example: connection-url=jdbc:hive2://127.0.0.1:10000/default

=== 5. VDB Deployment

Copy (deploy) the following VDB related files to the $JBOSS_HOME/standalone/deployments directory

----
src/vdb/hive-vdb.xml
src/vdb/hive-vdb.xml.dodeploy
----

Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate query.

== Query Demonstrations

==== Using the simpleclient example ====

1. Change your working directory to "${quickstart.install.dir}/simpleclient"
2. Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="portfolio" -Dsql="example query" -Dusername="xx" -Dpassword="xx"

The following sql can be used with -Dsql:

[source,sql]
----
SELECT * FROM EMPLOYEEVIEW
----
