
= JDG Local-Cache (Library Mode) Quickstart 

|===
|Level |Technologies |Target Product |Product Versions |Source

|Intermediate
|Teiid, Infinispan Library Mode
|DV, JDG
|DV 6.1+, JDG 6.5+
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

This quickstart demonstrates the following:

* how Teiid can access a cache of Java Objects stored in a local JDG cache running library mode.

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]
* JDG 6.5+ eap modules kit 

NOTE: can obtain JDG kit distributions on Red Hat's Customer Portal at https://access.redhat.com/jbossnetwork/restricted/listSoftware.html

== Setup

=== 1. JDG Setup

Install the JBoss Data Grid eap modules kit into the modules location for your JBoss AS - Teiid instance. See Red Hat: http://access.redhat.com to obtain the kit.

=== 2. Teiid Server Setup

* Build quickstart artifacts via

----
mvn clean install
----

This will build jdg-quickstart-jboss-as7-dist.zip in the target directory.

* Deploy the distribution kit

Unzip the target/jdg-quickstart-jboss-as7-dist.zip at the root of the JBOSS_HOME directory. This will deploy the pojo module and the cache configuration file.

* Update module dependencies

[Required] The org.infinispan.commons (slot="${jdg.slot}" or slot for version installed) module needs to have the pojo dependency added

[Optional] If the version of JDG modules you installed was not ${jdg.slot}, then update the following modules:

----
org.jboss.teiid.translator.infinispan.cache
org.jboss.teiid.resource-adapter.infinispan" slot="6"
----

* Configure resource-adapter

Open the file: {jbossas.server.dir}/docs/teiid/datasources/infinispan/infinispan-ds.xml, copy and paste the resource-adapter section it into the server configuration, under the section:

NOTE: the Infinispan cache will be configured using the infinispan.xml configuration file that's defined in the resource-adapter. Make sure the file name and the "ConfigurationFilenamForLocalCache" property match.

* Start the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

=== 3.  Install the infinispan-cache translator

----
cd ${JBOSS_HOME}/bin
./jboss-cli.sh --connect --file=../docs/teiid/datasources/infinispan/add-infinispan-cache-translator.cli
----

=== 4. deploy the VDB

Deploy VDB for reading the cache from directory src/vdb, opy files jdg-local-cache-vdb.xml and jdg-local-cache-vdb.xml.dodeploy to {jbossas.server.dir}/standalone/deployments

Open the admin console(http://localhost:9990/console) to make sure the VDB is deployed. See <<Query Demonstrations, Query Demonstrations>> below to demonstrate query.

== Query Demonstrations

1. Change your working directory to "${quickstart.install.dir}/simpleclient"
2. Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="Stocks" -Dsql="Insert into Stock (productId, symbol, price, companyname) Values (99, 'WMT', 45.35, 'Walmart')" -Dusername="teiidUser" -Dpassword="pwd"

or

Use a sql tool, like SQuirreL, to connect and issue following example queries(connect url jdbc:teiid:Stocks@mm://localhost:31000)

[source,sql]
.*Example Queries for using jdg-local-cache-vdb.xml*
----
select productId, symbol, price, companyname from Stock
select productId, symbol, price, companyname from Stock where symbol = 'RHT50'
select productId, symbol, price, companyname from Stock where price < '60.50'
Insert into Stock (productId, symbol, price, companyname) Values (99, 'WMT', 45.35, 'Walmart')
Update Stock set companyname='Apple Corp' where productId = 4
Delete From Stock where productId = 3
----

