#created on: Oct 30, 2006
package org.jboss.teiid.businessrules;

#list any import classes here.
import org.jboss.teiid.quickstart.data.MarketData;


rule "Price Is To High"
     dialect "mvel"
     no-loop
 when
   $r : MarketData(companyname : companyName, price : price, invalidMessage : invalidMessage )
   not MarketData( price < 50.0)
 then
   System.out.println("Price is Greater than $50 for " + companyname);
   modify ( $r ) { invalidMessage="Price is Greater than $50 " };
end 



   
