
= JDG Remote-Cache Quickstart using JDG Hot Rod client that supports Google Protocol Buffers for Serialization

|===
|Level |Technologies |Target Product |Product Versions |Source

|Intermediate
|Teiid, Infinispan, Hot Rod, Remote Query, Protobuf Annotations
|DV
|DV 6.3+, JDG 7.1+
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

This quickstart demonstrates how Teiid can connect to a remote JBoss Data Grid (JDG) as a data source, to query and update data in cache using the Hot Rod client protocol.

This example is using the protobuf annotations feature of JDG for configuring the protobuf definition file and the marshaller. 

== System requirements

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]
* link:../simpleclient/README.adoc[Simple Client]
* JDG Hot Rod client eap modules kit (used by Teiid to access the remote cache)
* JDG server kit (used as the remote server)

NOTE: You can obtain JDG kit distributions on Red Hat's Customer Portal at https://access.redhat.com/jbossnetwork/restricted/listSoftware.html

== Setup

=== 1. JDG setup

* Install the JDG server

* Configure JDG Cache

Edit the standalone.xml configuration in at ${JDG_HOME}/standalone/configuration.   Copy in the "local-cache" section into the configuration
within the infinispan:server subsystem.

[source,xml]
----
        <subsystem xmlns="urn:infinispan:server:core:8.3">
            <cache-container name="local" default-cache="default" statistics="true">
                .... 
                <local-cache name="datasourceCache" start="EAGER">
                    <locking striping="false" acquire-timeout="30000" concurrency-level="1000"/>
                    <transaction mode="NONE"/>
                </local-cache>

                ....
            </cache-container>
        </subsystem>
----

* Start JDG Server

It is assumed that you will be running both servers on the same box, therefore, start the JDG server by adding the following command line argument: 

-Djboss.socket.binding.port-offset=100

[source,xml]
.*Example*
----
./standalone.sh -Djboss.socket.binding.port-offset=100
----

For the purpose of this quick start, it assumes running both servers on the same machine and is expecting the JDG server to have its ports incremented. The port adjustment has been made in the setup.cli script to match the above offset.


=== 2. Build Teiid Quickstart

build the jdg-remote-cache quickstart

----
mvn -s ./settings.xml clean install
----

After building the quickstart, the `jdg-remote-cache-pojos-wildfly-dist.zip` should be found in the target directory. This zip will be used later, where it is deployed to the Teiid server.

=== 3. Setup Teiid Server

* Deploy pojo Module

a. Shutdown Teiid server, if not already. 

b. Take the target/jdg-remote-cache-pojos-wildfly-dist.zip and unzip at JBOSS_HOME

c. Install the JBoss Data Grid version of the hot rod client eap modules kit for EAP into /modules/ of your Teiid server instance. See Red Hat: http://access.redhat.com to obtain the kit.

* Start the server

To start the server, open a command line and navigate to the "bin" directory under the root directory of the Teiid server and run:

[source,xml]
----
./standalone.sh //For Linux
standalone.bat //for Windows
----

If Teiid isn't configured in the default configuration, append the following arguments to the command to specify the configuration `-c {configuration.file}`

[source,xml]
.*Example*
----
./standalone.sh -c standalone-teiid.xml
----

* Install the infinispan-hotrod translator

----
cd $\{JBOSS_HOME}/bin
./jboss-cli.sh --connect --file=../docs/teiid/datasources/infinispan-hotrod/add-ispn-hotrod-translator.cli
----


* Setup the JDG Cache to be accessed as a data source

The infinispan hotrod client resource adapter will be configured by executing a CLI script.

[source]
.*Setup JDG Data Source*
----
cd $\{JDG_HOME}/bin
./cli.sh --file=${PATH}/teiid-quickstarts/jdg-remote-cache/src/scripts/create-infinispan-hotrod-protobuf-ds.cli
----

NOTE:  see  {JBOSS_HOME}/docs/teiid/datasources/infinispan-hotrod/readme.txt for all the options for configuring the resource-adapter.
 

=== 4. deploy the VDB

Deploy for reading/writing to a remote cache, copy files jdg-remote-cache-vdb.xml and jdg-remote-cache-vdb.xml.dodeploy to {JBOSS_HOME}/standalone/deployments


== Query Demonstrations

1. Change your working directory to "${quickstart.install.dir}/simpleclient"
2. Use the simpleclient example to run the following queries:

Example: mvn exec:java -Dvdb="People" -Dsql="Insert into Person (id, name, email) Values (100, 'TestPerson', 'test@person.com')" -Dusername="teiidUser" -Dpassword="pwd"

or

Use a sql tool, like SQuirreL, to connect and issue following example query:

NOTE: do not do a `SELECT * FROM Person`, because you will get a serialization error, because the Person class is not serializable.

1.  Queries for reading/writing to a remote cache via VDB People

* connect: jdbc:teiid:People@mm://{host}:31000 

[source,sql]
.*Example Query SQL*
----
select name, email, id from Person 
Insert into Person (id, name, email) Values (100, 'TestPerson', 'test@person.com');
Insert into Person (id, name, email) Values (200, 'TestPerson2', 'test2@person.com');

select name, email, id from Person where id = 100
Update Person set name='testPerson 100' where id = 100 then - select name, email, id from Person 


Insert into Address (id, Address, City, State) Values (200, '1212 Stratford', 'Williamsburg', 'VA')

select a.id, a.name, b.Address, b.City, b.State from Person as a, Address as b WHERE a.id = b.id


Insert into PhoneNumber (id, number) Values (200, '603-351-3022');

select a.id, a.name, b.number from Person as a, PhoneNumber as b WHERE a.id = b.id


delete from Person where id = 100
select name, email, id from Person
----
