
= Simple Java Client

|===
|Level |Technologies |Target Product |Product Versions |Source

|Beginners
|Teiid, JDBC
|DV
|DV 6.1
|https://github.com/teiid/teiid-quickstarts
|===

== What is it?

The sample client example can be used to test your sql queries against any server running a compatible Teiid Runtime and has an active VDB. This example will also be referenced by many of the other quick starts as a means to test suggested queries. Be sure to read the README for that quick start in order to setup the environment correctly before executing a test query. 

The link:src/main/java/JDBCClient.java[JDBCClient.java] is the example code that shows a developer the basic connection logic that can be used to connect to a Teiid instance running in a {{ book.asName }}.

The program expects four arguments . The pom.xml defines these arguments in the pom.xml:

[source,xml]
----
<mainClass>JDBCClient</mainClass>
<arguments>
    <argument>localhost</argument>  <!-- host -->
    <argument>31000</argument>   <!--  port -->
    <argument>${vdb}</argument>
    <argument>${sql}</argument>
</arguments>
----

NOTE: Notice that the and are preset. To point to a different server and/or port, change "localhost" and/or "31000" arguments, respectively, in the pom.xml.

== Prerequisites

* link:../README.adoc#_downloading_and_installing_java[Java]
* link:../README.adoc#_downloading_and_installing_maven[Maven]
* link:../README.adoc#_downloading_and_installing_teiid[Teiid Server]

== Build

Build the project by running

[source,xml]
----
mvn clean install
----

== Execution

To execute a sql query using the simpleclient, use the following format:

[source,xml]
----
mvn exec:java -Dvdb="<vdb>" -Dsql="<sql>" -Dusername="<username>" -Dpassword="<password>"
----

[source,java]
.*A Example Executions*
----
mvn exec:java -Dvdb="twitter" -Dsql="select * from tweet where query= 'jboss'"
mvn exec:java -Dvdb="Portfolio" -Dsql="select * from Stock"
mvn exec:java -Dvdb="ExcelVDB" -Dsql="select * from PersonalHoldings"
----

NOTE: The query is in quotes so that it is understood as a single argument. To run more advanced queries, it would be better a fully featured Java client, such as link:./SQuirreL.adoc[SQuirreL Client].
