
= SQuirreL Client

Here are steps of how to use SquirreL (http://squirrel-sql.sourceforge.net/) to access the VDB. SquirreL is JDBC client tool, using which you can access any database. 


* Download this tool from the link provided, and instal using directions here http://squirrel-sql.sourceforge.net/#installation

* Download the Teiid java driver from Teiid's download page http://teiid.jboss.org/downloads/

* Start the SquirreL, and then add a driver for Teiid. See the screen shots here http://squirrel-sql.sourceforge.net/index.php?page=screenshots use following settings

----
Name: Teiid
Example URL: jdbc:teiid:<vdb-name>@mm[s]://<host>:<port>
Website URL: http://teiid.org
----

NOTE: you need to add the JDBC driver download above in the "Extra Class Path" tab, click "List Drivers" and select "Class Name" at the bottom as "org.teiid.jdbc.TeiidDriver"
    
* Click on Alias tab, and create an alias, using the driver created above. use the following settings

----
Name: VDBNAME
Driver: Teiid
URL: jdbc:teiid:VDBNAME.1@mm://127.0.0.1:31000
User: <user>
Password: <password>
----

Test your connection, then press OK. Then right click on alias created, and choose "connect" to connect to the VDB and issue SQL queries and see the results.

